version: "3.9"
services:
  db:
    image: mongo:6.0.2
    environment:
      - MONGODB_DATABASE="devchallenge"
    ports:
      - 27017:27017
  neo4j:
    image: neo4j:4.4.9-enterprise
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - "./.neo4j_scripts:/var/lib/neo4j/import/neo4j_scripts/"