version: "3.9"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - "mongo"
      # - "neo4j"
    ports:
      - 8080:8080
  node:
    image: node:16.14.2
    working_dir: /app
    volumes:
      - "./:/app"
  mongo:
    image: mongo:6.0.2
    environment:
      - MONGODB_DATABASE="devchallenge"
    ports:
      - 27017:27017