version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
  node:
    image: node:16.14.2
    working_dir: /app
    volumes:
      - "./:/app"